import = ["/home/logank/.config/alacritty/themes/challengerdeep.toml"]

[font]
size = 18.0

[font.bold]
family = "Mononoki Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font Mono"
style = "Regular"

[font.normal]
family = "Mononoki Nerd Font Mono"
style = "Regular"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations_theme_variant = "dark"
dynamic_title = true
